#pragma once



enum item_t
{
   ITEM_TYPE_CLUB = 1,
   ITEM_TYPE_STONE_OF_DEFIANCE,
   ITEM_TYPE_NAUGHTY_LIST,
   ITEM_TYPE_SILVER_SHIELD,
   ITEM_TYPE_GOLDEN_SHIELD,
   ITEM_TYPE_SILVER_SWORD,
   ITEM_TYPE_GOLDEN_SWORD,
   ITEM_TYPE_KEY
};



#define SPRITES_GRID_FILENAME "sprites_grid-x.png"
#define SPRITES_GRID_SPRITE_WIDTH 48
#define SPRITES_GRID_SPRITE_HEIGHT 48
#define SPRITES_GRID_SPRITE_SCALING 3



